# Generated by Django 2.1.3 on 2018-12-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(default='index', max_length=32, unique=True, verbose_name='URL别名'),
        ),
    ]
