# Generated by Django 2.1.3 on 2018-12-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20181223_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, default='fa-fire', max_length=32, verbose_name='图标'),
        ),
    ]
