# Generated by Django 2.1.3 on 2018-12-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_auto_20181225_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_menu',
        ),
    ]
